### ISSUE TITLE
Customise user interface 

### ISSUE THREAD

**Issue by supriyatambe131995** [amzn/fire-app-builder#32]
Hi ,

I have list of categories on left and the corresponding list of videos related to all the categories on the right. 
Currently , i can select any of the categories on the left and the focus goes to the video list on the right.
what i need is  , if a user selects a category from left , then , only video list related to that category should be listed/shown and other videos (unrelated to the categories i selected) should be hidden/not shown

Also want that if consider i have category list like home , about ,setting,video ,song then if user select home screen then all category list accessible after that while click down button list goes down and other category display and change show in in category list but consider if i select video category only the list of video category should be accessible. and i also want to design different screen for home category and for other i want design same screen like give in sample git repository

**Comment by levonlevonian** [comment]
Hi there,

Regrettably we currently don’t support that custom UI experience you are looking for out of the box. It sounds like you want an experience similar to this Stack Overflow question: https://stackoverflow.com/questions/30629982/how-to-make-a-browsefragment-with-only-one-row-visible 

I have notified the dev team about your request. In the meantime, since this is an open source project, please feel free to investigate this feature yourself and see if it's something you could implement. Thanks!
