### ISSUE TITLE
Can't Change Colors

### ISSUE THREAD

**Issue by rwatts9942** [amzn/fire-app-builder#4]
Is anyone else having trouble changing the background color?  I am following the documentation that is here:

https://developer.amazon.com/public/solutions/devices/fire-tv/docs/fire-app-builder-customize-look-and-feel

None of the changes I put in the custom.xml file seem to affect anything on the main browse screen.  I was able to change the background color on the splash screen.

**Comment by rwatts9942** [comment]
There are two custom.xml files that must be updated and the documentation doesn't make it clear which one is used (one is under App and the other is under TVUIComponent).

**Comment by sindy-amazon** [comment]
Hello from Amazon!

The background colors in custom.xml are used by the Full Browse layout, as that is a solid color, but not by the default layout for Fire App Builder.
 
For the default browse layout, an image is currently used for the background to accomplish the fade around the image in the top right. An immediate fix for this would be to create a PNG and name it bg_generic.png. Place this in the custom.xml file of the TVUIComponent to override the existing one. Unfortunately, the PNG will need to be created similarly to the one we currently have, i.e. with the top right corner missing, otherwise it will cover the image of the selected content.
 
In a future version, we have plans to make it easier to customize the colors and not have to work with a background image.

[I've posted this information as a Knowledge Base Article on our developer forums site as well.](https://forums.developer.amazon.com/articles/48799/how-to-change-background-colors-in-fire-app-builde.html)

**Comment by tomjoht** [comment]
I updated the documentation on [customizing the homepage layout](https://developer.amazon.com/public/solutions/devices/fire-tv/docs/fire-app-builder-customize-look-and-feel#customize-the-homepage-layout). I also included the Photoshop source file in case you want to easily change the background image.
