### ISSUE TITLE
Override Current Logo Size Constraints 

### ISSUE THREAD

**Issue by paingha** [amzn/fire-app-builder#50]
Hi,
I was wondering if there was anyway to override the current logo size constraints of 356 x 108 for both the splash screen and the home screen. The current size constraints are making my logo look compressed. 
Thank you!

**Comment by levonlevonian** [comment]
Hi there,

I assume your logo is larger and the compressed look is the result of scaling the logo? The system resizes only larger than 356x108px logos down to that size. I would recommend using a logo of exactly 356x108px (or smaller), which will not be resized (it will not be scaled up). When exporting your logo from the graphics application (such as Illustrator or Photoshop, etc) specify those dimensions, or if your logo is of different proportions, you can fill the remaining space with transparent pixels. Please give it a try and let us know if that works for you.

Reference: https://developer.amazon.com/docs/fire-app-builder/customize-look-and-feel.html

**Comment by paingha** [comment]
Hi @levonlevonian thanks for the quick reply. The logo is exactly the required size as I used Illustrator to ensure that. If it was possible to increase the constraints from 356x108px it would really help as the logo has text in it that is not so readable when the size is 356x108px. Thank you

**Comment by levonlevonian** [comment]
Hi paingha,

Thanks for additional details. Text in an image can be tricky with Android possibly optimizing larger file sizes which may result in a loss of clarity. Perhaps SVG / VectorDrawable format could solve this issue: https://developer.android.com/guide/topics/graphics/vector-drawable-resources
Its advantage is that it can be scaled without any loss of quality (and hopefully clarity), so it's definitely worth a try in this case of a logo with text.

Alternatively, since this is an open source project, please feel free to modify it for your logo dimensions. Thanks!
