### ISSUE TITLE
Is it possible to have multiple closed captions ?

### ISSUE THREAD

**Issue by gaamus** [amzn/fire-app-builder#53]
Hi,

Currently, I can only use one closed caption, do fire app builder support multiple closed captions ? like other fire app, they have an slide menu in the right when click "CC" button but I didn't see that, is it already included ? or not ?

Thanks

**Comment by levonlevonian** [comment]
Hi gaamus,

As far as I know, multiple closed captions are supported. Does your media include multiple closed captions, or only one?

**Comment by gaamus** [comment]
Hi @levonlevonian,

thanks for quick reply, yes my media has multiple closed captions such as English, Spanish, and Vietnamese. I have added English, Spanish and Vietnamese but when click "CC", it only choose English, how can we choose other option like Spanish and Vietnamese ?

**Comment by levonlevonian** [comment]
Hi gaamus,

Apologies I misunderstood your original question. We only support one closed caption at this time.  The first valid closed caption will be used.  At the moment, we don't have plans to add this functionality.  However, because this is an open source project, developers could choose to add their own button for this use case if needed. Thanks!
